### ISSUE TITLE
TopLevelMetadata offset redundant in bounds?

### ISSUE THREAD

**Issue by martinheidegger** [connormanning/ept#2]
What is the difference in the TLM between the minimum of the bounds and the offset? It seems like the data is redundant?

**Comment by connormanning** [comment]
Spatial scale/offset information has been removed, in favor of generic scale/offset per dimension.  Offset is explicitly stated to avoid magic/implicit rules - for example you might use the midpoint or the minimum point as your offset depending on preference.
