### ISSUE TITLE
Move hierarchyStepSize into hierarchyStorage

### ISSUE THREAD

**Issue by martinheidegger** [connormanning/ept#3]
There is the latent possibility to implement a hierarchy that, instead of a regular step sizes uses indicators in the files about when to introduce a new step. If we offer people to implement different hierarchy formats, I think we might want to keep the option open about what parameters are used for the format and move hierarchyStepSize as a "parameter", i.e.:

```
.hierarchyStorage = "potree"
.hierarchyStepSize = 400
```
👇

```
.hierarchyStorage = "potree+400"
```

**Comment by connormanning** [comment]
Hierarchy step information in general no longer exists.  This information is now determined dynamically from the hierarchy.
