### ISSUE TITLE
Tick documentation issues

### ISSUE THREAD

**Issue by martinheidegger** [connormanning/ept#4]
I tried to read and comprehend the `.tick` documentation but I struggle with it.

1. Does `tick` have any influence on the hierarchy structure (from what I understand: no)
2. Does `tick` have any influence on the point storage (from what I understand: no)

If both of these are indeed "no" then my question is:

3. Why is `tick` not a "metadata"?

**Comment by connormanning** [comment]
1. Indirectly, sort.  In the sense that different `ticks` values will result in different resulting hierarchies for the same input data.
2. No.
3. I don't fully understand this portion - `ticks` **is** part of the metadata and is useful for computing the voxelized point spacing for the octree - are you suggesting to remove it?  Or move it somewhere else?

**Comment by martinheidegger** [comment]
Before going to 3.: How are the hierarchies different? Structurally not _(right?)_; the structure still stays in the slippy-map format?! The hierarchy files also don't change? Do only the amounts of points change?

**Comment by connormanning** [comment]
Yes the structure maintains the same format, and yes - only the amounts of points change.  However this can cause the number of levels and number of nodes in the tree to change.

For example a dataset of `8*8*8 = 512` evenly spaced points will result in only one data file with `ticks=8`: `0/0/0/0` containing all 512 points (with overflow points disabled).  If the same dataset were built with `ticks=4`, then `0/0/0/0` would contain only 64 points at half the resolution in each spatial dimension, with the remainder of points being in the 8 child nodes at depth `1`.

`ticks` is directly convertible to the spacing or resolution of the nodes.  The spacing of the root node in a single dimension can be calculated as `cubeWidth / ticks` (for example in potree this happens [here](https://github.com/connormanning/potree/blob/ept/src/PointCloudEptGeometry.js#L55)), which is doubled at each subsequent depth.

**Comment by martinheidegger** [comment]
Okay, thank you for the clarification. As it doesn't have implications for a reader of the EPT format I was confused why its in the "main" specification and rather in the "build" information. Thanks you very much for the potree link. I forgot that potree does two level selection of nodes (one during loading - which i remembered, one in the visualization). Now, with your explanation I am emotionally conflicted 😅 .

**Comment by connormanning** [comment]
The `ticks` value has been renamed to `span`, retaining the same meaning.  See connormanning/entwine#151
