### ISSUE TITLE
Data file schema

### ISSUE THREAD

**Issue by martinheidegger** [connormanning/ept#5]
One of the problems with the potree schema is the dealing with millions of files in the same folder. The potree format solves this by allowing for hierarchies: `0/0/0/0.bin` instead of `0-0-0-0.bin`. Would you be open to change the storage structure to make it easier on folder-listings?

**Comment by hobu** [comment]
One of the problems of `0/0/0/0.bin` is that a `0.bin` file is useless by itself. There might be some instances where you wouldn't want directories. I wonder if there is a metadata that could be provided in the info call that tells the consumer which pattern to be using. It doesn't really matter from a caching or service standpoint, right?

**Comment by martinheidegger** [comment]
To my knowledge there is no difference in http-caching or service. `/` and `-` are treated as "equal" in http or S3. One of the obvious problems is that the EPT writer needs to create & remember the folders it has created, or move all the files after the fact. Which shouldn't be that much of an issue, but will surely add a few filesystem calls.

In regards to adding a "setting" to choose the file system, there are a few questions in my mind:

- Doesn't it put pressure on reader-implementations to implement various ways to read files?
- How flexible are the data storage systems?
    - potree allows prefixes ([`octreeDir`](https://github.com/potree/potree/blob/develop/docs/potree-file-format.md))
    - potree allows splits by amount of hierarchy levels ([`hierarchyStepSize`](https://github.com/potree/potree/blob/develop/docs/potree-file-format.md))
- The slippy-map structure is nice but it has increasing amount of files per depth:
    65k per dimension at level 16. Would it be better to also allow a "oct-tree" setting that has a
    fixed max per folder?
- Would the hierarchy.json file table change notation? From `0-0-0-0` to `0/0/0/0` in order to indicate  
    that the number has a direct relation to the filesystem?

**Comment by connormanning** [comment]
For EPT 1.0 this is going to remain as `0-0-0-0` with no option for `0/0/0/0`.  Some good reasons have already been discussed above.  The 2 approaches are largely the same with a slight edge to 

For implementation simplicity this will not be configurable at this time.  If this truly becomes a non-hypothetical problem (i.e. groups with real-world issues: "I have problem X that would be solved if I could use 0/0/0/0 format") this could be revisited in a future revision.
