### ISSUE TITLE
ept laz files being 1.35 times bigger than original laz

### ISSUE THREAD

**Issue by tomvantilburg** [connormanning/ept#7]
It went from 26mb to 35 mb
Not perse a bug, I'm just curious what's causing it. I would expect some overhead but not that much.

What's more, when I go back to one laz file with pdal it ends up being 28mb

**Comment by hobu** [comment]
spatially sorting the data like EPT does disrupts the efficiency of LAZ. While the coordinates of a spatially sorted file are close together and do not have many bits of change, the other attributes (especially GPSTime) will not. This is why you see more bloat in the files.

**Comment by tomvantilburg** [comment]
Ofcourse!
Enlightening :)
